import { test, expect } from '@playwright/test';
import { setupSecondSlide, issueSecondSlide, origin } from './promo_second_slide_browser_fixture.mjs';
const artifacts = '.tasks/TASK-143-T2-FT-005-W10';
for (const portrait of [false, true]) test(`second slide configuration, late fill and replay ${portrait ? 'portrait reduced' : 'landscape'}`, async ({ page }) => {
  test.setTimeout(60_000);
  await page.setViewportSize(portrait ? { width: 600, height: 1000 } : { width: 1280, height: 720 });
  await page.emulateMedia({ reducedMotion: portrait ? 'reduce' : 'no-preference' });
  const requests = await setupSecondSlide(page);
  const enabled = page.locator('#promo-second-slide-enabled');
  const seconds = page.locator('#promo-second-slide-seconds');
  await expect(enabled).not.toBeChecked();
  await enabled.check(); await seconds.fill('1.5');
  await page.getByRole('button', { name: 'Сохранить второй слайд', exact: true }).click();
  expect(await page.evaluate(() => localStorage.getItem('face-moment.promo-second-slide'))).toBeNull();
  await seconds.fill('5');
  await page.getByRole('button', { name: 'Сохранить второй слайд', exact: true }).click();
  await expect(page.locator('.promo-second-slide-panel [role="status"]')).toContainText('Сохранено');
  await page.reload(); await expect(enabled).toBeChecked(); await expect(seconds).toHaveValue('5');
  expect(await page.evaluate(async () => (await import('/client/promo-display-preferences.js')).readPromoSecondSlide())).toEqual({ enabled: true, seconds: 5 });
  await page.screenshot({ path: `${artifacts}/configuration-${portrait ? 'portrait' : 'landscape'}.png` });
  await issueSecondSlide(page);
  await expect(page.locator('.promo-card:not(.promo-gallery)')).toBeVisible();
  const qr = await page.locator('[data-qr-content]').getAttribute('data-qr-content');
  expect(qr).toBe(`${origin}/q?ticket=fixture`);
  await expect.poll(() => requests.filter(r => r.method === 'PUT' && r.path.endsWith('/display')).length, { timeout: 10000 }).toBe(1);
  const grid = page.locator('.promo-gallery');
  await expect(grid).toBeVisible({ timeout: 5000 });
  await expect(grid.locator('.promo-gallery-cell')).toHaveCount(12);
  await expect(grid.locator('svg, h2, p')).toHaveCount(0);
  await expect(grid.locator('.promo-gallery-cell').nth(4).locator('img')).toHaveCount(0);
  if (!portrait) {
    const frames = await grid.evaluate(el => el.getAnimations().map(a => a.effect.getKeyframes().map(k => Object.keys(k))));
    expect(frames.flat(2)).not.toContain('transform');
  }
  await page.screenshot({ path: `${artifacts}/late-grid-${portrait ? 'portrait' : 'landscape'}.png` });
  await expect(grid.locator('.promo-gallery-cell').nth(4).locator('img')).toHaveCount(1, { timeout: 5000 });
  await expect(grid.locator('.promo-gallery-cell').nth(5).locator('img')).toHaveCount(0);
  const geometry = await grid.evaluate(el => ({ width: el.getBoundingClientRect().width, height: el.getBoundingClientRect().height, columns: getComputedStyle(el).gridTemplateColumns.split(' ').length, rows: getComputedStyle(el).gridTemplateRows.split(' ').length }));
  expect(geometry).toEqual({ ...page.viewportSize(), columns: 4, rows: 3 });
  await page.screenshot({ path: `${artifacts}/grid-${portrait ? 'portrait' : 'landscape'}.png` });
  await expect(grid).toHaveCount(0, { timeout: 12000 });
  await expect(page.locator('.promo-ad-handoff')).toBeHidden({ timeout: 2500 });
  const before = requests.length;
  await page.mouse.click(1, page.viewportSize().height - 2);
  await expect(grid).toBeVisible();
  await expect(page.locator('[data-qr-content]')).toHaveCount(0);
  expect(requests.slice(before).filter(r => r.path.endsWith('/display') || r.path.endsWith('/attempts'))).toEqual([]);
  await page.screenshot({ path: `${artifacts}/replay-${portrait ? 'portrait' : 'landscape'}.png` });
  await expect(grid).toHaveCount(0, { timeout: 10000 });
  await expect(page.locator('.promo-ad-handoff')).toBeHidden({ timeout: 2500 });
  await page.goto(`${origin}/#configuration`); await enabled.uncheck();
  await page.getByRole('button', { name: 'Сохранить второй слайд', exact: true }).click();
  await page.goto(`${origin}/#advertising`);
  await page.mouse.click(1, page.viewportSize().height - 2);
  await expect(page.locator('.promo-card:not(.promo-gallery)')).toBeVisible();
  await expect(page.locator('[data-qr-content]')).toHaveAttribute('data-qr-content', qr);
  await expect(grid).toHaveCount(0);
  expect(requests.filter(r => r.method === 'PUT' && r.path.endsWith('/display'))).toHaveLength(1);
});
